name: Pull Request Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-openj9
          java-version: '11'

      - name: Test the sample
        run: cd sample && ./gradlew cleaningServiceAll && cd ..

      - name: Build the library module
        run: ./gradlew lib:test lib:jar

      - name: Build the plugin module
        run: ./gradlew plugin:test plugin:jar

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            lib/build/reports/**