name: Pull Request Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the library module
        run: ./gradlew lib:test lib:jar
      - name: Build the plugin module
        run: ./gradlew plugin:test plugin:jar
      - name: Test the sample
        run: cd sample && ./gradlew cleaningServiceAll